# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
publishdir = "docs"
baseurl = "https://dhirajk.info/"
#relativeURLs = "True"
# Language used
languageCode = "en-us"
# Website title
title = "Dhiraj Kuttichirayil"
# Theme used
theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/post/ folder
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150

# This links to the page about.md
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

# Make the tags and categories pages accessible directly from the navbar.
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -130

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """A little about me, Dhiraj Kuttichirayil"""
    # Author of the site
    authorName = "Dhiraj Kuttichirayil"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "https://avatars.githubusercontent.com/u/25961063?v=4"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false



# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
